In [9]:
import matplotlib.pyplot as plt 
import pandas as pd
import math
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM
from keras.layers import GRU 

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

import psycopg2
from sklearn.model_selection import train_test_split

from matplotlib import pyplot as plt 
%matplotlib inline
plt.rcParams['figure.facecolor'] = 'white'
import seaborn as sns

import keras_functions
from keras_functions import *

In [2]:
con = psycopg2.connect(database='codeforces', user='Joy')
cur = con.cursor()

In [3]:
binvars = get_categorical_variables([
    'all_participanttypes',
    'all_tags',
    'all_language'
])

# Initial pipeline

In [4]:
with open('set_train.txt') as f:
    train_handles = [h.strip() for h in f.readlines()]
with open('set_test.txt') as f:
    test_handles = [h.strip() for h in f.readlines()]

In [172]:
user_batch = 10

In [238]:
reload(keras_functions)
x= keras_functions.get_user_data('2difficult4me', binvars=binvars, month=3, maxtimepts=500)

431
707
711


In [239]:
x[0][['contestid', 'hours_solve_to_contest', 'hours_submit_to_solve']]

contestid  hours_solve_to_contest  hours_submit_to_solve
0         431             2845.192222               0.048611
27        431           389081.500278         -386416.957500
23        431             2665.932778               0.000000
22        431             2940.943611               0.119722
21        431             2941.441111               0.000000
18        431             3001.756389               2.233056
16        431             3073.891667               0.873889
15        431             3368.156667               0.000000
14        431             3368.349444               0.010556
13        431             3368.963056               0.000000
12        431             3369.780556               0.000000
17        431             3003.854444               0.465556
10        431             3333.950556               0.185278
1         431             2844.671944               0.017778
11        431             3250.106667              81.485556
3         431             3469.384444               0.010833
4         431             3467.276389               0.255278
5         431             3468.520833               0.438056
2         431             2843.190833               0.783056
9         431             3333.546389               0.000000
6         431             3466.128333               0.000000
7         431             3130.336111               0.154722
8         431             3334.453889               0.000000
31        431                0.372500               0.000000
30        431                1.756944               0.000000
29        431                1.528611               0.000000
28        431                1.688333               0.000000
19        431             2604.411944               0.237778
26        431             2573.621389               0.000000
25        431             2573.636389               0.000000
24        431             2665.811111               0.000000
20        431             2600.674444               2.065278

In [226]:
for c in x[0].columns:
    print c

COMPILATION_ERROR
CONTESTANT
GNU C
GNU C++
GNU C++11
MEMORY_LIMIT_EXCEEDED
MS C++
OK
PRACTICE
RUNTIME_ERROR
TIME_LIMIT_EXCEEDED
VIRTUAL
WRONG_ANSWER
contestid
newrating
oldrating
points
problem_rating
rank
smoothed_3months
shortest paths
2-sat
greedy
meet-in-the-middle
matrices
number theory
constructive algorithms
chinese remainder theorem
implementation
ternary search
schedules
dsu
dfs and similar
graph matchings
string suffix structures
math
probabilities
fft
divide and conquer
two pointers
trees
data structures
flows
sortings
expression parsing
dp
hashing
bitmasks
*special
geometry
combinatorics
graphs
brute force
games
binary search
strings
PRESENTATION_ERROR
TESTING
CRASHED
CHALLENGED
REJECTED
FAILED
SKIPPED
IDLENESS_LIMIT_EXCEEDED
PARTIAL
GYM
OUT_OF_COMPETITION
Scala
Delphi
JavaScript
PyPy 2
PyPy 3
Perl
Factor
D
Mysterious Language
FPC
Ada
F#
Java 8
Picat
Ruby
Java 8 ZIP
Pike
MS C#
Python 2
Python 3
Secret_171
Kotlin
J
Ocaml
Java 6
Go
Roco
GNU C11
Befunge
Rust
PHP
FALSE
Mono C#


In [139]:
#np.any(np.isnan(test.delta_smoothed_3months))

AttributeError: 'list' object has no attribute 'delta_smoothed_3months'

In [120]:
reload(keras_functions)
X = []
Y = []
lens = [0] * user_batch
runsum = 0
for i in range(user_batch):
    filename = 'rnn_train/' + train_handles[i] + ".csv"
    print filename
    x, y = keras_functions.get_user_data(train_handles[i], binvars=binvars, month=3, maxtimepts=500)
    X.append(x)
    Y.append(y)
    runsum += x.shape[0]
    lens[i] = runsum

rnn_train/2difficult4me.csv
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
Name: delta_smoothed_3months, dtype: float64
9    NaN
10   NaN
11   NaN
Name: delta_smoothed_3months, dtype: float64
12   NaN
Name: delta_smoothed_3months, dtype: float64
rnn_train/priyanka_1998.csv
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
Name: delta_smoothed_3months, dtype: float64
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
Name: delta_smoothed_3months, dtype: float64
13     NaN
14    0.05
15     NaN
Name: delta_smoothed_3months, dtype: float64
20      NaN
21   -0.205
Name: delta_smoothed_3months, dtype: float64
16     NaN
17   -0.08
18     NaN
19     NaN
Name: delta_smoothed_3months, dtype: float64
27   NaN
28   NaN
Name: delta_smoothed_3months, dtype: float64
22      NaN
23      NaN
24      NaN
25   -0.205
26    0.050
Name: delta_smoothed_3months, dtype: float64
rnn_train/vatr.csv
0   -0.09
1   -0.09
2   -0.09
3   -0.09
Name: delta_smoothed_3months, dtype: f

418    0.050769
419    0.050769
420    0.033516
421    0.033516
Name: delta_smoothed_3months, dtype: float64
422    0.033516
423    0.033516
424    0.307143
425    0.307143
426    0.307143
427    0.307143
428    0.307143
429    0.307143
430    0.307143
Name: delta_smoothed_3months, dtype: float64
431    0.307143
432    0.066071
Name: delta_smoothed_3months, dtype: float64
433    0.066071
434   -0.224167
Name: delta_smoothed_3months, dtype: float64
435   -0.224167
436   -0.123333
437   -0.123333
438   -0.123333
Name: delta_smoothed_3months, dtype: float64
439   -0.123333
440    0.005000
441    0.005000
442    0.005000
443    0.005000
Name: delta_smoothed_3months, dtype: float64
444    0.005
445    0.105
Name: delta_smoothed_3months, dtype: float64
446    0.10500
447   -0.10625
Name: delta_smoothed_3months, dtype: float64
448   -0.10625
449   -0.12075
Name: delta_smoothed_3months, dtype: float64
rnn_train/KMPArthas.csv
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: delta_smoothed_

In [116]:
X_batch = np.concatenate(X, axis=0)

In [118]:
Y

[array([ nan,  nan,  nan]),
 array([ nan,  nan,  nan,  nan,  nan,  nan,  nan]),
 array([-0.09   , -0.09   ,  0.21   , -0.09   , -0.1575 , -0.48   ,
         0.14   ,  0.315  ,  0.315  , -0.045  , -0.045  ,  0.10375,  0.35   ]),
 array([        nan,         nan, -0.1275    , -0.1275    , -0.14178571,
        -0.14178571, -0.3775    , -0.29928571, -0.03916667, -0.11208333,
        -0.02025   , -0.29928571, -0.04875   ,  0.07625   , -0.14178571,
        -0.08783333, -0.08783333, -0.06175   , -0.08783333, -0.11666667,
         0.223     ,  0.207     , -0.06708333, -0.06708333,  0.207     ,
         0.207     ,  0.06966667,  0.06966667, -0.29928571, -0.29928571,
         0.105     ,  0.105     ,  0.07      ,  0.046     ,  0.046     ,
        -0.05357143,  0.09544643,  0.03034722,  0.15822222,  0.15822222,
         0.20944444,  0.20944444,  0.16      ,  0.165     , -0.05652778,
         0.04509091, -0.03607143, -0.066875  , -0.12706349, -0.12706349,
         0.01797619, -0.05321429, -0.08952

In [101]:
epochs = 5

In [ ]:
for e in range(epochs):
    